[package]
name = "voxel_raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.34.0"
winit = "0.28.0"
vulkano-shaders = "0.34.0"
nalgebra = { version = "0.33.2", features = ["bytemuck"] }
png = "0.17.16"